### ISSUE TITLE
通过ini文件来配置小说源站点，这个我借鉴一下

### ISSUE THREAD

**Issue by ljhzds** [ling7334/Novel-crawler#1]
我也在搞一个自己的小说站，我想提供txt下载功能，不知道你有木有想法，如果一章一章的获取感觉会很慢。。

**Comment by ling7334** [comment]
txt文件抓取倒是没什么问题，只要网站提供，就抓取的到，主要是在读取分章的问题。
本来最近是想把抓取配置改成正则的（BS实在太慢）。
txt功能应该会另外做成一块功能。
既然你提了，我想想看怎么弄。总之先加入txt抓取功能。

**Comment by ljhzds** [comment]
有个问题，ini里面配置的 hchuag text获取的时候收到<br/>影响，所以提取不到 text正文。。

**Comment by ling7334** [comment]
几个commit前好像是有这个问题，最新的解决了。如果你用的是最新更新的，能说一下哪本小说，我验证看看。

**Comment by ghost** [comment]
![image](https://cloud.githubusercontent.com/assets/15902558/16725752/4b906f72-478b-11e6-8041-9b318a6a83d3.png)
出现这个是什么原因
