### ISSUE TITLE
都不能访问

### ISSUE THREAD

**Issue by onebit1984** [ling7334/Novel-crawler#3]
![image](https://cloud.githubusercontent.com/assets/4945086/24441427/24c86010-148c-11e7-9dc4-e62d65308e29.png)

**Comment by ling7334** [comment]
最近在搞新版本。好像这些网站修改过了，貌似反爬虫升级了。

**Comment by ling7334** [comment]
xs111貌似确实死了

**Comment by ling7334** [comment]
奇怪，本地运行可以搜到，但heroku上确实无法连接。可能是被墙了。

**Comment by ling7334** [comment]
确认是墙的问题，墙外服务器访问不了。如果有兴趣，可以下载到本地用。
